### ISSUE TITLE
有没有可能不限制react版本？

### ISSUE THREAD

**Issue by lulious** [CJY0208/react-activation#149]
冒昧的问一下，有没有可能不限制react版本，给低版本的react一条活路（捂脸哭）

**Comment by CJY0208** [comment]
是有多低 (狗头)



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月25日(周四) 晚上8:29
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [CJY0208/react-activation] 有没有可能不限制react版本？ (Issue #149)




 
冒昧的问一下，有没有可能不限制react版本，给低版本的react一条活路（捂脸哭）
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lulious** [comment]
react 15.6

**Comment by CJY0208** [comment]
现在支持16+，已经很低了 (笑哭)，为啥不升级？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月25日(周四) 晚上8:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [CJY0208/react-activation] 有没有可能不限制react版本？ (Issue #149)




 
react 15.6
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lulious** [comment]
好早之前的老项目，很庞杂，一直在迭代开发，基本不会升级了。

**Comment by CJY0208** [comment]
可以试试我的另一个库 [react-router-cache-route](https://github.com/CJY0208/react-router-cache-route)

当前库需要基于 16+ 的 fiberNode 进行缓存，暂时没法再往下降了

**Comment by junhui75165** [comment]
@CJY0208 有没有办法自定义方法插入一个缓存页面，用于微前端的子应用如果是vue或者其他非react的时候也可以共用一个tabs

**Comment by CJY0208** [comment]
不太理解你的场景，听起来和 activation 无关，activation 的 keep alive 只是保持某个 React 组件不被卸载
