### ISSUE TITLE
请问，可以在页面初始化时触发useActivate吗？

### ISSUE THREAD

**Issue by yanglinga** [CJY0208/react-activation#151]
![image](https://user-images.githubusercontent.com/44689400/144579205-05829d48-a57d-4676-97ef-395b6b7889ae.png)
现在只有第二次进入页面时才会触发useActivate

**Comment by CJY0208** [comment]
第一次渲染可以用 useEffect [ ] 模拟 onMounted 呀，useActived 只用于缓存后再激活的场景的

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月3日(周五) 下午5:31
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [CJY0208/react-activation] 请问，可以在页面初始化时触发useActivate吗？ (Issue #151)




 

 现在只有第二次进入页面时才会触发useActivate
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
