### ISSUE TITLE
在指定页面按 f5 刷新后. 该页面无法被缓存. 

### ISSUE THREAD

**Issue by lingting** [CJY0208/react-activation#152]
复现地址: http://react.ballcat.cn/
账号: lingting
密码: lingting
(该环境为演示环境. 所有人都可以进行任意操作. 无保密需要)

复现步骤:
1. 进入任意页面
2. 按 f5 或 ctrl+r 或其他 刷新页面
3. 修改任意组件状态或者在搜索框中填写内容
4. 进入其他页面.在切换回来. 页面重新渲染

注: 该bug无法在本地复现. 只有打包后再线上才能复现

**Comment by lingting** [comment]
源码: https://github.com/ballcat-projects/ballcat-ui-react

**Comment by CJY0208** [comment]
keep-alive 只是存留于缓存的 keep alive 哦，没法实现页面刷新后依然存留，如果需要做的话，需要配合 storage 来保存状态了，可以看看 ahooks 的 useLocalStorage



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月3日(周五) 下午5:41
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [CJY0208/react-activation] 在指定页面按 f5 刷新后. 该业务无法被缓存.  (Issue #152)




 
复现地址: http://react.ballcat.cn/
 账号: lingting
 密码: lingting
 (该环境为演示环境. 所有人都可以进行任意操作. 无保密需要)
 
复现步骤:
  
进入任意页面 

按 f5 或 ctrl+r 或其他 刷新页面 

修改任意组件状态或者在搜索框中填写内容 

进入其他页面.在切换回来. 页面重新渲染 
 
注: 该bug无法在本地复现. 只有打包后再线上才能复现
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lingting** [comment]
> 


理解错我的意思啦. 我不是指在 f5刷新后. 页面依旧是 f5刷新之前的页面. 
就是正常的缓存失效了. 

下面是正常情况:
![正常情况](https://user-images.githubusercontent.com/59352063/144599679-1484910e-62a9-4b1e-97c6-9862f7fdd3d6.gif)

但是如果我在系统用户页面按 f5 刷新后.  系统用户页面就没法正常缓存了

**Comment by lingting** [comment]
下面是我录的失效情况

![失效情况](https://user-images.githubusercontent.com/59352063/144601079-40594da4-e80a-4b13-8e05-54907cfc470a.gif)

**Comment by CJY0208** [comment]
看了一下例子，KeepAlive 确实是把组件缓存了，但似乎是组件内部发生了刷新，看代码找不太出来是什么原因

**Comment by lingting** [comment]
> 


我找了下不同.  
其他页面是被渲染在  RouteHistory 组件下的. 
第一个页面直接被渲染. 没有被 RouteHistory 组件包裹. 

在这种情况下. 切换到第一个页面时, 缓存的父级组件应该会被销毁.  是不是会导致缓存失效
从其他页面切换第一个页面同理..  

但是我目前找不到第一个页面没有被 RouteHistory 包裹的原因........

**Comment by CJY0208** [comment]
先留着也行，不过这会儿还没空仔细找原因

**Comment by lingting** [comment]
> 先留着也行，不过这会儿还没空仔细找原因


哈哈. 你忙. 我关了. 找bug去
